Repository CrayLabs/SmartDashboard, pull requests merged in 2024-04, with the labels that each got.

#53 Auto-post release PR to develop
  .github/workflows/release.yml
  doc/changelog.rst
Labels: area: CI/CD

#52 Telemetry doc updates
  README.md
  doc/changelog.rst
  doc/overview.rst
Labels: area: docs

#55 Correct header styling
  doc/changelog.md
Labels: area: docs, ignore-for-release
